module.exports = {
  auth: 'Not Authenticated',
  unknown_error: 'Unknown error',
  bad_request: 'Bad request',
  vendor_error: 'Something went wrong with provider, please try again',
  database_error: 'Database error, please contact IT support',

  fullname_required: 'Nama lengkap wajib diisi',

  nik_required: 'NIK wajib diisi',
  nik_length_fix_16: 'NIK wajib 16 digit angka',
  nik_unique: 'NIK sudah terdaftar',
  
  username_required: 'Username wajib diisi',
  username_unique: 'Username sudah terdaftar',
  username_max_30: 'Username max 30 characters',
  username_alphanumeric: 'Username is alphanumeric only',

  email_unique: 'Email sudah terdaftar',
  phone_unique: 'Phone sudah terdaftar',
  wechat_unique: 'Wechat sudah terdaftar',
  
  password_required: 'Password wajib diisi',
  password_8_16: 'Password minimal 8 karakter dan maksimal 16 karakter',
  password_match: 'Password dan konfirmasi password tidak sesuai',
  password_wrong: 'Password anda tidak sesuai',
  password_alphanumeric: 'Password must be alphanumeric only',
  confirmation_password_required: 'Konfirmasi password wajib diisi',
  
  status_required: 'Status wajib diisi',
  status_not_valid: 'Status tidak valid',
  
  role_required: 'Role wajib diisi',
  role_not_valid: 'Role tidak valid',
  
  theme_required: 'Theme name wajib diisi',
  theme_not_found: 'Theme tidak ditemukan',
  color_required: 'Color wajib diisi',
  theme_unique: 'Theme unique',

  calendar_not_found: 'Kalender tidak ditemukan',
  calendar_name_required: 'Kalender name wajib diisi',
  calendar_for_province_exist: 'Kalender untuk provinsi ini sudah ada',
  
  admin_not_found: 'Admin tidak ditemukan',
  user_not_found: 'User tidak ditemukan',
  province_not_valid: "Province not valid",
  city_not_valid: "City not valid",

  membercard_not_found: 'Member card not found',

  lunar_required: 'Nama lunar kalender wajib diisi',
  year_required: 'Tahun wajib diisi',
  year_numeric: 'Tahun wajib angka',

  admin_not_active: 'Admin tidak aktif',
  user_not_active: 'User tidak aktif',
  province_not_found: 'Provinsi tidak ditemukan',
  province_unique: 'Provinsi sudah terdaftar',
  province_required: 'Provinsi wajib diisi',
  city_unique: 'Kota sudah terdaftar',
  occasion_type_required: 'Occasion type wajib diisi',
  point_required: 'Point wajib diisi',
  scope_required: 'Occasion scope wajib diisi',

  title_required: 'Judul wajib diisi',
  subtitle_required: 'Sub judul wajib diisi',
  image_required: 'Gambar wajib diisi',
  description_required: 'Deskripsi wajib diisi',
  title_max_255: 'Judul maksimal 255 karakter',
  subtitle_max_500: 'Subtitle maksimal 500 karakter',
  description_max_1500: 'Deskripsi maksimal 1500 karakter',

  banner_unique: 'Banner sudah ada, silahkan coba judul lain',

  bulletin_unique: 'Bulletin sudah ada, silahkan coba judul lain',
  bulletin_not_found: 'Bulletin tidak ditemukan',

  banner_not_found: 'Banner tidak ditemukan',

  // User 
  no_anggota_required: 'User unique id wajib diisi',
  phone_required: 'Phone number wajib diisi',
  phone_not_valid: 'Phone must be numeric',
  phone_min_max_10_14: 'Phone min 10 and max 14 number',
  email_required: 'Email wajib diisi',
  email_not_valid: 'Email tidak valid',
  gender_required: 'Gender wajib diisi',
  gender_not_valid: 'Gender tidak valid',
  // first_name_latin_required: 'Latin first name wajib diisi',
  // first_name_latin_alpha: 'Latin first name must be alpha only',
  // first_name_latin_max_200: 'Latin first name max 200 characters',
  // last_name_latin_required: 'Latin last name wajib diisi',
  // last_name_latin_alpha: 'Latin last name must be alpha only',
  // last_name_latin_max_200: 'Latin last name max 200 characters',
  // chinese_name_required: 'Chinese name wajib diisi',
  // chinese_name_max_200: 'Chinese name max 200 characters',
  // image_required: 'Image wajib diisi',
  // address_required: 'Address wajib diisi',
  // address_max_300: 'Address max 300 characters',
  // date_of_birth_required: 'Date of birth wajib diisi',
  // date_of_birth_not_valid: 'Date of birth is not a valid date',
  place_of_birth_required: 'Tempat / Provinsi lahir wajib dipiliht',
  city_required: 'Kota wajib dipilih',
  // postal_address_required: 'Postal address wajib diisi',
  // postal_address_max_6: 'Postal address max 6 digit',
  // month_required: 'Month wajib diisi',
  // month_numeric: 'Month must be numeric',
  // day_required: 'Day wajib diisi',
  // day_numeric: 'Day must be numeric',
  // events_required: 'Event wajib diisi',
  event_name_required: 'Event name wajib diisi',
  // title_required: 'Title broadcast wajib diisi',
  // description_required: 'Description broadcast wajib diisi',
  // title_max_200: 'Title max 200 characters',
  // description_max_200: 'Description max 200 characters',
  // life_status_required: 'Life status wajib diisi',
  // user_broadcast_required: 'User broadcast wajib diisi',
  // user_broadcast_min_1: 'User broadcast wajib diisi',
  // token_expired: 'Token expired',
  // expired_date_required: 'Expired date wajib diisi',
  // title_required: 'Title wajib diisi',
  // occasion_unique: 'Occasion title unique',
  // occasion_not_found: 'Occasion tidak ditemukan',
  // image_not_valid: 'Image not valid',
  // failed_upload_image: 'Failed upload image',
  // image_size_over: 'Image size maximum 2mb',
  // point_not_enough: 'Point is not enough',
  // already_registered: 'You already redeem this event',
  // occasion_expired: 'Event already ended',
  // file_size: 'File size is too large'
}