module.exports = {
  username_required: 'Username required',
  username_unique: 'Username already registered',
  username_max_30: 'Username max 30 characters',
  username_alphanumeric: 'Username is alphanumeric only',
  password_required: 'Password required',
  password_8_16: 'Password min 8 and max 16 characters',
  password_match: 'Confirmation password and password not match',
  password_wrong: 'Wrong password, please try again',
  password_alphanumeric: 'Password must be alphanumeric only',
  confirmation_password_required: 'Confirmation password required',
  status_required: 'Status required',
  status_not_valid: 'Status not valid',
  role_required: 'Role required',
  role_not_valid: 'Role not valid',
  theme_required: 'Theme name required',
  theme_not_found: 'Theme not found',
  color_required: 'Color required',
  theme_unique: 'Theme unique',
  calendar_not_found: 'Calendar not found',
  calendar_name_required: 'Calendar name required',
  admin_not_found: 'Admin not found',
  user_not_found: 'User not found',
  unknown_error: 'Unknown error',
  bad_request: 'Bad request',
  admin_not_active: 'Admin not active',
  user_not_active: 'User not active',
  province_not_found: 'Province not found',
  province_unique: 'Province unique',
  province_required: 'Province required',
  city_unique: 'City unique',
  auth: 'Not Authenticated',
  // User 
  no_anggota_required: 'User unique id required',
  phone_required: 'Phone number required',
  email_required: 'Email required',
  email_not_valid: 'Invalid email',
  gender_required: 'Gender required',
  gender_not_valid: 'Gender not valid',
  first_name_latin_required: 'Latin first name required',
  first_name_latin_alpha: 'Latin first name must be alpha only',
  first_name_latin_max_200: 'Latin first name max 200 characters',
  last_name_latin_required: 'Latin last name required',
  last_name_latin_alpha: 'Latin last name must be alpha only',
  last_name_latin_max_200: 'Latin last name max 200 characters',
  chinese_name_required: 'Chinese name required',
  image_required: 'Image required',
  address_required: 'Address required',
  address_max_300: 'Address max 300 characters',
  date_of_birth_required: 'Date of birth required',
  date_of_birth_not_valid: 'Date of birth is not a valid date',
  place_of_birth_required: 'Place of birth required',
  month_required: 'Month required',
  month_numeric: 'Month must be numeric',
  day_required: 'Day required',
  day_numeric: 'Day must be numeric',
  events_required: 'Event required',
  event_name_required: 'Event name required',
  title_required: 'Title broadcast required',
  description_required: 'Description broadcast required',
  title_max_200: 'Title max 200 characters',
  description_max_200: 'Description max 200 characters',
  life_status_required: 'Life status required',
  user_broadcast_required: 'User broadcast required',
  user_broadcast_min_1: 'User broadcast required',
  token_expired: 'Token expired',
  expired_date_required: 'Expired date required',
  title_required: 'Title required',
  occasion_unique: 'Occasion title unique',
  occasion_not_found: 'Occasion not found',
  image_not_valid: 'Image not valid',
  failed_upload_image: 'Failed upload image',
  image_size_over: 'Image size maximum 2mb'
}