module.exports = {
  fullname_required: 'Nama lengkap wajib diisi',

  nik_required: 'NIK wajib diisi',
  nik_length_fix_16: 'NIK wajib 16 digit angka',
  nik_unique: 'NIK sudah terdaftar',
  
  username_required: 'Username required',
  username_unique: 'Username already registered',
  email_unique: 'Email already registered',
  phone_unique: 'Phone already registered',
  wechat_unique: 'Wechat already registered',
  username_max_30: 'Username max 30 characters',
  username_alphanumeric: 'Username is alphanumeric only',
  password_required: 'Password wajib diisi',
  password_8_16: 'Password minimal 8 karakter dan maksimal 16 karakter',
  password_match: 'Password dan konfirmasi password tidak sesuai',
  password_wrong: 'Password anda tidak sesuai',
  password_alphanumeric: 'Password must be alphanumeric only',
  confirmation_password_required: 'Confirmation password required',
  status_required: 'Status required',
  status_not_valid: 'Status not valid',
  role_required: 'Role required',
  role_not_valid: 'Role not valid',
  theme_required: 'Theme name required',
  theme_not_found: 'Theme not found',
  color_required: 'Color required',
  theme_unique: 'Theme unique',
  calendar_not_found: 'Calendar not found',
  calendar_name_required: 'Calendar name required',
  admin_not_found: 'Admin not found',
  user_not_found: 'User tidak ditemukan',
  unknown_error: 'Unknown error',
  bad_request: 'Bad request',
  admin_not_active: 'Admin not active',
  user_not_active: 'User not active',
  province_not_found: 'Province not found',
  province_unique: 'Province unique',
  province_required: 'Province required',
  city_unique: 'City unique',
  occasion_type_required: 'Occasion type required',
  point_required: 'Point required',
  scope_required: 'Occasion scope required',
  auth: 'Not Authenticated',
  // User 
  no_anggota_required: 'User unique id required',
  phone_required: 'Phone number required',
  phone_not_valid: 'Phone must be numeric',
  phone_min_max_10_14: 'Phone min 10 and max 14 number',
  email_required: 'Email wajib diisi',
  email_not_valid: 'Email tidak valid',
  gender_required: 'Gender wajib diisi',
  gender_not_valid: 'Gender tidak valid',
  // first_name_latin_required: 'Latin first name required',
  // first_name_latin_alpha: 'Latin first name must be alpha only',
  // first_name_latin_max_200: 'Latin first name max 200 characters',
  // last_name_latin_required: 'Latin last name required',
  // last_name_latin_alpha: 'Latin last name must be alpha only',
  // last_name_latin_max_200: 'Latin last name max 200 characters',
  // chinese_name_required: 'Chinese name required',
  // chinese_name_max_200: 'Chinese name max 200 characters',
  // image_required: 'Image required',
  // address_required: 'Address required',
  // address_max_300: 'Address max 300 characters',
  // date_of_birth_required: 'Date of birth required',
  // date_of_birth_not_valid: 'Date of birth is not a valid date',
  place_of_birth_required: 'Tempat / Provinsi lahir wajib dipiliht',
  city_required: 'Kota wajib dipilih',
  // postal_address_required: 'Postal address required',
  // postal_address_max_6: 'Postal address max 6 digit',
  // month_required: 'Month required',
  // month_numeric: 'Month must be numeric',
  // day_required: 'Day required',
  // day_numeric: 'Day must be numeric',
  // events_required: 'Event required',
  // event_name_required: 'Event name required',
  // title_required: 'Title broadcast required',
  // description_required: 'Description broadcast required',
  // title_max_200: 'Title max 200 characters',
  // description_max_200: 'Description max 200 characters',
  // life_status_required: 'Life status required',
  // user_broadcast_required: 'User broadcast required',
  // user_broadcast_min_1: 'User broadcast required',
  // token_expired: 'Token expired',
  // expired_date_required: 'Expired date required',
  // title_required: 'Title required',
  // occasion_unique: 'Occasion title unique',
  // occasion_not_found: 'Occasion not found',
  // image_not_valid: 'Image not valid',
  // failed_upload_image: 'Failed upload image',
  // image_size_over: 'Image size maximum 2mb',
  // point_not_enough: 'Point is not enough',
  // already_registered: 'You already redeem this event',
  // occasion_expired: 'Event already ended',
  // file_size: 'File size is too large'
}